version: '3'

networks:
  lsystems_db_net:
    ipam:
      config:
        - subnet: 172.50.0.0/24

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    networks:
      lsystems_db_net:
        ipv4_address: 172.50.0.10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  mongo:
    image: mongo
    restart: always
    networks:
      lsystems_db_net:
        ipv4_address: 172.50.0.11
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      lsystems_db_net:
        ipv4_address: 172.50.0.12
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
    ports:
      - 8082:8081
  pgadmin:
    image: dpage/pgadmin4:2020-05-22-github1
    restart: always
    ports:
    - 8000:80
    networks:
      lsystems_db_net:
        ipv4_address: 172.50.0.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin